// MINIMUM SPARKS REQUIRED TO GET A CODE
export const MIN_SPARKS = 10;

// BOARD_SIZE
export const BOARD_SIZE = 15;

// TIMER (IN SECONDS)
export const TIMER = 60;

// SNAKE SPEED
export const SNAKE_SPEED = 300;
export const SNAKE_SPEED_INCREMENT = 10;
